[options]
HoldPkg      = pacman glibc
Architecture = auto

# 🇬🇧 Misc options
# 🇫🇷 Options diverses
# 🇪🇸 Opciones varias
# 🇮🇹 Opzioni varie
# 🇵🇹 Opcções diversas
Color
CheckSpace
ILoveCandy
VerbosePkgLists
DisableDownloadTimeout
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# 🇬🇧 Unofficial mirrors
# 🇫🇷 Mirrors non officiels
# 🇪🇸 Mirros no oficiales
# 🇮🇹 Mirror non ufficiali
# 🇵🇹 Mirrors não oficiais
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
