name: Publishing the configured and generated extension

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checking the repository out
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Releasing
        uses: softprops/action-gh-release@v1

  publish:
    runs-on: ubuntu-latest
    container: archlinux:multilib-devel

    steps:
      - name: Installing Git and Node.js
        run: pacman -Syu --noconfirm --needed git nodejs npm

      - name: Checking the repository out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Installing the dependencies
        run: npm ci

      - name: Publishing for VSCE
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publishing for Open VSX
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}
